sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jJ43E3pWjdIMF13Qh6Eil8XSGHJD4KTPsiYslDqEQOtDezlrOhuJClDNi5jbsuH4stGraNxyhRyo9jsJw8P5TugxujwUDtrF6OZfmfYZu0r147GU3tFfAMVpkcA7BcSyH9Uexr0YOkmS8I2wgs29SgS1f167xxsJKy3lCh5fZj/o9jyrxxC6EDbgiLusNy6NWqQoWvoU2f1NIkrmBIa9P9+h6vRdd0ZZVak3aSXcMdlgVUZnggb1jogOgMrBmiurBknHtl7Z6MH+zmCmEdTDxvS09KBeI8yrRDNVz8+YdA54SrXOiXKfCtWsh2bT24FSIGdn0KC1k6BB+QlpopGfG+FDRf/6G3yshB7uQeLcFzWTp9zzqrzS2ZG8eUQSp+TdQAW1ZGN8b6g5YLRFX1yBpPuiMQcxvi40bAdGie9LAjdm/yxW1h7TkoMgEKodQ89dH5flJFLmn3o5lJuR4HwLGNOhg42r1ZWihfBPZDWxvRghsk0IPikynWPk2TOo/5O1omq6JmjvWzKHceVhWKRJxLwqByZuzLETcrlJ+gjIvTemGBFuH5i2rW4QqRvRgGDLHLiEUpEeBFSf4gWNflGmzZ7z5r0+U5QAyrkD89UIlbsB1WNyyeae+2UkdhyN/5fHxAdkHTKz1NQ4rwD8FXmGcm7LxW1uDIdc/Bq6U1+PnCk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Bucky-O-Connor--A-Tale-of-the-Unfenced-Border_1809
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy